server:
  port: 8083
spring:
  application:
    name: auth-api
  datasource:
    url: jdbc:mysql://localhost:3306/authenticationdb
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true