server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: invoice-route
          uri: http://localhost:8081/api/v1/invoices/
          predicates:
            - Path=/api/v1/invoices/**
          filters:
            - name: ApiKeyFilter

        - id: product-route
          uri: http://localhost:8082/api/v1/products/
          predicates:
            - Path=/api/v1/products/**
          filters:
            - name: ApiKeyFilter

auth:
  service:
    url: http://localhost:8083/api/v1/auth