server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: invoice-route
#          uri: http://localhost:8081/api/v1/invoices/
          uri: ${EUREKA_URI:http://localhost:8081}
          predicates:
            - Path=/api/v1/invoices/**
          filters:
            - name: ApiKeyFilter

        - id: product-route
#          uri: http://localhost:8082/api/v1/products/
          uri: ${EUREKA_URI:http://localhost:8082}
          predicates:
            - Path=/api/v1/products/**
          filters:
            - name: ApiKeyFilter

auth:
  service:
#    url: http://localhost:8083/api/v1/auth
     url: ${EUREKA_URI:http://localhost:8083}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true